### ISSUE TITLE
13. Lỗi hiển thị ở mục Multimedia

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#11]
- Bài chính không có title. 
- Xem ở bản dành cho màn hình bé thì ảnh bài chính bị ăn vào ảnh và chữ của các tin bên cạnh
![lỗi hiển thị ở mục Multimedia](https://user-images.githubusercontent.com/82023545/113804230-59086180-9788-11eb-9d28-56bb010b8b3d.jpg)

**Comment by longtv123456** [comment]
@quangtruongthanh  trèn thêm class="img-fluid" vào trong thẻ <img>

**Comment by quangtruongthanh** [comment]
done
