### ISSUE TITLE
14. Mục English hiển thị thiếu tin

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#12]
- Chỉ hiển thị 3 tin thường phía dưới thay vì 4 tin như các mục khác nên chân
![Mục english](https://user-images.githubusercontent.com/82023545/113804446-bac8cb80-9788-11eb-88bb-b32f880a14ac.jpg)
 bị so lệch với mục bên cạnh

**Comment by quangtruongthanh** [comment]
done
