### ISSUE TITLE
15. Ở trang chuyên mục, khoảng cách giữa title và ảnh sát quá trông xấu và không đồng nhất với trang chủ

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#13]
- Chỉnh để giống phía ngoài trang Home là ok
![Khoảng cách giữa title và ảnh sát quá trông xấu và không đồng nhất với trang chủ](https://user-images.githubusercontent.com/82023545/113804657-362a7d00-9789-11eb-95a8-4b9c46aca305.jpg)

**Comment by longtv123456** [comment]
Thêm class="mb-3" vào thẻ <img>

**Comment by quangtruongthanh** [comment]
anh @longtv123456 mb-3 nó chỉ tăng khoảng cách title với phía dưới, còn khoảng cách với ảnh ở trên vẫn như cũ

**Comment by longtv123456** [comment]
thêm class="mb-3" vào thẻ img để ảnh cách tile

**Comment by longtv123456** [comment]
sửa đoạn này cũng thêm mb-3 để title có khoảng cách với sapo

<h2 class="font-weight-bold post-title post-title-cat mb-3"><a href="/cong-nghe/vi-sao-mam-oto-thuong-duoc-gan-cuc-chi/20210406095418475" rel="bookmark" title="Vì sao mâm ôtô thường được gắn cục chì?">Vì sao mâm ôtô thường được gắn cục chì?</a></h2>

**Comment by quangtruongthanh** [comment]
done
