### ISSUE TITLE
16. Biểu tượng kính lúp bé và không thẳng hàng với biểu tượng cụm menu bên cạnh

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#14]
![Biểu tượng kính lúp bé và không thẳng hàng với biểu tượng cụm Menu](https://user-images.githubusercontent.com/82023545/113804963-c072e100-9789-11eb-83d7-1d0136498332.jpg)

**Comment by longtv123456** [comment]
thay thế cho anh đoạn này @quangtruongthanh 
<div class="d-flex justify-content-center h-100">
					<div class="searchbar">
					  <input class="search_input" type="text" name="" placeholder="Tìm kiếm">
					  <a href="#" class="search_icon"><i class="fas fa-search"></i></a>
					</div>
				</div>

thay bằng 

<div class="d-flex justify-content-center h-100">
					<form class="search">
					  <div class="search__wrapper">
						<input type="text" name="" placeholder="Search for..." class="search__field">
						<button type="submit" class="fa fa-search search__icon"></button>
					  </div>
					</form>
				</div>

**Comment by quangtruongthanh** [comment]
em đã thay html của anh @longtv123456
