### ISSUE TITLE
17. Bỏ bớt quảng cáo này, chỉ để hiển thị 1 quảng cáo đầu tiên

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#15]
- HIện tại trên trang đang có 3,4 quảng cáo banner này lặp lại
- Chỉ giữ lại 1 quảng cáo còn lại bỏ
![Quảng cáo](https://user-images.githubusercontent.com/82023545/113805142-2e1f0d00-978a-11eb-9418-682ee1bbaf9d.jpg)

**Comment by quangtruongthanh** [comment]
done
