### ISSUE TITLE
18. Phần Nổi bật không hiện thị thanh trượt để kéo thủ công bằng tay 

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#16]
- Anh Long xem tham khảo bên bọn Doanh nhân Việt Nam

**Comment by tuansandro** [comment]
![Uploading thanh trượt.jpg…]()

**Comment by longtv123456** [comment]
thay đoạn này
<h4 class="font-time text-uppercase">Nổi bật</h4>
			  <div class="bg-DNVN-nhat py-3 pl-3 pr-0 mb-2">
					  <div class="hidden-scrollbar">
						<div class="inner">
							<ul class="list-unstyled">
								<li><a class="" href="">Mẹ đảm nấu cháo chim câu đậu xanh cà rốt cho bé ăn dặm, ngửi mùi là muốn ăn ngay</a></li><hr>
								<li><a class="" href="">7 thực phẩm bé càng ăn càng thông minh, nhất là loại thứ 4 không phải ai cũng biết</a></li><hr>
								<li><a class="" href="">7 thực phẩm giúp mẹ bầu ngủ ngon trong suốt thai kỳ</a></li><hr>
								<li><a class="" href="">Đêm tân hôn mẹ chồng hốt hoảng khi con dâu khóc nức nở</a></li><hr>
								<li><a class="" href="">Cuộc tấn công của Iskander của Nga vào biên giới Thổ Nhĩ Kỳ là một lời cảnh báo đối với Tổng thống Erdogan?</a></li><hr>
								<li><a class="" href="">Ngày cưới tôi 'chết đứng' tại chỗ khi bóc món quà cưới sếp của vợ tặng cho cô ấy</a></li><hr>
								<li><a class="" href="">Sai lầm uống sữa khiến con bị thiếu máu, chậm lớn, nhiều mẹ Việt đang mắc phải</a></li><hr>
								<li><a class="" href="">Bộ Kế hoạch và Đầu tư đề xuất xây dựng Đà Nẵng thành trung tâm tài chính khu vực </a></li><hr>
								<li><a class="" href="">Mẹ đảm nấu cháo chim câu đậu xanh cà rốt cho bé ăn dặm, ngửi mùi là muốn ăn ngay</a></li><hr>
								<li><a class="" href="">Cuộc tấn công của Iskander của Nga vào biên giới Thổ Nhĩ Kỳ là một lời cảnh báo đối với Tổng thống Erdogan?</a></li><hr>
								<li><a class="" href="">Ngày cưới tôi 'chết đứng' tại chỗ khi bóc món quà cưới sếp của vợ tặng cho cô ấy</a></li><hr>
								<li><a class="" href="">Sai lầm uống sữa khiến con bị thiếu máu, chậm lớn, nhiều mẹ Việt đang mắc phải</a></li><hr>
								<li><a class="" href="">Bộ Kế hoạch và Đầu tư đề xuất xây dựng Đà Nẵng thành trung tâm tài chính khu vực </a></li><hr>
								<li><a class="" href="">Mẹ đảm nấu cháo chim câu đậu xanh cà rốt cho bé ăn dặm, ngửi mùi là muốn ăn ngay</a></li>
							</ul>
						</div>
					</div>
				  </div>

Bằng

<h4 class="font-time text-uppercase">Nổi bật</h4>
			  		<div class="scrollbar" id="style-1">
						<div class="force-overflow">
							<ul class="list-unstyled">
								<li><a class="" href="">Mẹ đảm nấu cháo chim câu đậu xanh cà rốt cho bé ăn dặm, ngửi mùi là muốn ăn ngay</a></li><hr>
								<li><a class="" href="">7 thực phẩm bé càng ăn càng thông minh, nhất là loại thứ 4 không phải ai cũng biết</a></li><hr>
								<li><a class="" href="">7 thực phẩm giúp mẹ bầu ngủ ngon trong suốt thai kỳ</a></li><hr>
								<li><a class="" href="">Đêm tân hôn mẹ chồng hốt hoảng khi con dâu khóc nức nở</a></li><hr>
								<li><a class="" href="">Cuộc tấn công của Iskander của Nga vào biên giới Thổ Nhĩ Kỳ là một lời cảnh báo đối với Tổng thống Erdogan?</a></li><hr>
								<li><a class="" href="">Ngày cưới tôi 'chết đứng' tại chỗ khi bóc món quà cưới sếp của vợ tặng cho cô ấy</a></li><hr>
								<li><a class="" href="">Sai lầm uống sữa khiến con bị thiếu máu, chậm lớn, nhiều mẹ Việt đang mắc phải</a></li><hr>
								<li><a class="" href="">Bộ Kế hoạch và Đầu tư đề xuất xây dựng Đà Nẵng thành trung tâm tài chính khu vực </a></li><hr>
								<li><a class="" href="">Mẹ đảm nấu cháo chim câu đậu xanh cà rốt cho bé ăn dặm, ngửi mùi là muốn ăn ngay</a></li><hr>
								<li><a class="" href="">Cuộc tấn công của Iskander của Nga vào biên giới Thổ Nhĩ Kỳ là một lời cảnh báo đối với Tổng thống Erdogan?</a></li><hr>
								<li><a class="" href="">Ngày cưới tôi 'chết đứng' tại chỗ khi bóc món quà cưới sếp của vợ tặng cho cô ấy</a></li><hr>
								<li><a class="" href="">Sai lầm uống sữa khiến con bị thiếu máu, chậm lớn, nhiều mẹ Việt đang mắc phải</a></li><hr>
								<li><a class="" href="">Bộ Kế hoạch và Đầu tư đề xuất xây dựng Đà Nẵng thành trung tâm tài chính khu vực </a></li><hr>
								<li><a class="" href="">Mẹ đảm nấu cháo chim câu đậu xanh cà rốt cho bé ăn dặm, ngửi mùi là muốn ăn ngay</a></li>
							</ul>
						</div>
					</div>

**Comment by quangtruongthanh** [comment]
done
