### ISSUE TITLE
19. Vẫn bị khoảng trống trên trang Home

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#17]
- Nhờ anh Long chỉnh lại kích thước một số QC hiện đang quá to
![Khoảng trống trên trang HOme](https://user-images.githubusercontent.com/82023545/113805819-68d57500-978b-11eb-8203-1073f4c7b320.jpg)

**Comment by longtv123456** [comment]
Cứ cắt và xếp lại QC ở giữa đi phần banner bên phải anh sẽ chỉnh sau cho bằng
