### ISSUE TITLE
20. Lỗi về hiển thị thiếu tin trên cụm cover trên giao diện Mobile

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#18]
- Hiển thị thiếu các tin cover, tin Nổi bật trên giao diện Mobile, cụ thể là hiện cụm cover hiện tại chỉ hiển thị duy nhất 1 tin cover.

**Comment by longtv123456** [comment]
cái này Q có chỉnh hiển thị mobile thế nào không

**Comment by quangtruongthanh** [comment]
@tuansandro như giao diện cũ, bản mobile cũng hạn chế số tin. hiện tại tôi đang để là 1 tin thôi. ông muốn lên bao nhiêu thì để tôi sửa

**Comment by tuansandro** [comment]
- Ông hiển thị giúp tôi 3 tin Cover và 3 tin Nổi bật. Tổng cộng là 6 tin. 
- Tuy nhiên hiện ảnh và title của tin hiển thị thêm đó đang bé hơn so với cỡ chung ở giao diện Mobile, nhờ ông với anh Long chỉnh lại hộ
![170399113_249860590207344_1122000029638033849_n](https://user-images.githubusercontent.com/82023545/114187433-2f129300-9972-11eb-9bc8-e12e680be11b.png)
