### ISSUE TITLE
21. Điều chỉnh để hiển thị thêm tin ở các chuyên mục bản Mobile

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#19]
- Hiện tại ở bản Mobile chỉ hiển thị 1 tin chính và 1 tin thường.
- Chỉnh lại là hiển thị 1 tin chính + 2 tin thường

**Comment by longtv123456** [comment]
Bản tke anh đâng để nhưu Tuấn rồi Quang xem lại hộ anh nhé

**Comment by quangtruongthanh** [comment]
done
