### ISSUE TITLE
2. Font chữ đang không đồng nhất ở phần trang Chuyên mục và trang đọc bài chi tiết

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#2]
+ Ở phần trang chuyên mục, title của cụm 5 tin đầu tiên ở trên đầu đang chưa bôi đen, kích thước chữ cũng đang quá bé

**Comment by tuansandro** [comment]
![Trang chuyên mục](https://user-images.githubusercontent.com/82023545/113683035-f498c400-96ed-11eb-9b74-62fe1a2388e0.jpg)

**Comment by quangtruongthanh** [comment]
font chữ này thì ôn gnhowf anh Long đi

**Comment by longtv123456** [comment]
<a class="font-weight-bold" href="/cong-nghe/bang-gia-dien-thoai-realme-thang-4-2021-them-san-pham-moi/20210406030053286" rel="bookmark" title="Bảng giá điện thoại Realme tháng 4/2021: Thêm sản phẩm mới">Bảng giá điện thoại Realme tháng 4/2021: Thêm sản phẩm mới</a>

Thêm thẻ này class="font-weight-bold"

**Comment by longtv123456** [comment]
Hiểu không Quang ơi class đó nằm trong thẻ <a> nhé

**Comment by quangtruongthanh** [comment]
vâng  anh @longtv123456

**Comment by quangtruongthanh** [comment]
done
