### ISSUE TITLE
22. Phần Tin hot xem trên điện thoại Android vẫn bị chữ quá to

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#20]
- Chỉnh lại cỡ chữ phù hợp
![cỡ chữ phần tin Hot](https://user-images.githubusercontent.com/82023545/114129881-a4a64100-9929-11eb-8c3d-8a0c15f836ec.png)

**Comment by longtv123456** [comment]
cái này lạ thật đấy, GS có mấy con idroi test thử xem tn
