### ISSUE TITLE
25. Chỉnh lại các biểu tượng ở chân trang về 1 dòng để đẹp hơn

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#23]
- Hiện có một số biểu tượng như biểu tượng FB, biểu tượng RSS, biểu tượng email đang 1 mình 1 dòng
- Ngoài ra, 2 số điện thoại có thể căn chỉnh lại để gọn lại thành 1 dòng là đẹp nhất. Ví dụ có thể bỏ Bold là sẽ ok.
- Căn chỉnh lại để thu gọn dòng trống để đẹp và hợp lý hơn

![170488999_207889480707251_1165808726126533125_n](https://user-images.githubusercontent.com/82023545/114130683-4da16b80-992b-11eb-89a9-24f1b143047e.png)

**Comment by longtv123456** [comment]
GS xem lại hình như của GS để máy hiển thị font chữ to hơn bình thường thì phải

**Comment by longtv123456** [comment]
anh để hiển thị đc như của chú thì màn hình phải xuống còn 271px
