### ISSUE TITLE
26. Kích thước của title ở các chuyên mục hiển thị trên Mobile chưa đồng nhất

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#24]
- Ví dụ kích thước title ở mục Bất động sản to hơn rất nhiều so với mục Made in Vietnam
- Về cơ bản là các mục ở bản PC mà đứng riêng lẻ chữ sẽ to khi xem trên Mobile, còn các mục xếp đứng cạnh nhau ở trên bản PC thì khi hiển thị trên Mobile chữ sẽ bị bé
![168415474_3708105542648680_160512098051040752_n](https://user-images.githubusercontent.com/82023545/114131072-141d3000-992c-11eb-9a69-3d2231d403b1.png)
![171197656_268965544856374_3188971000035004965_n](https://user-images.githubusercontent.com/82023545/114131080-17b0b700-992c-11eb-83fe-9ab5a2baa9e2.png)

**Comment by longtv123456** [comment]
Thông số y hêt nhau đấy xem trên ip thì ko có hiện tượng đó
