### ISSUE TITLE
28. Các quảng cáo ở trang detail bị mất trên bản Mobile

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#26]
- Các quảng cáo cần được giữ nguyên như bản hiện tại, đặc biệt là ở phần trang detail.
- Hiện đang mất ít nhất 2 quảng cáo ở trên phần đầu bài viết chi tiết bản Mobile:
+ 1 quảng cáo phía trên logo ở header
+ 1 quảng cáo ở ngay phía dưới sapo
![quảng cáo phía trên logo](https://user-images.githubusercontent.com/82023545/114131712-4f6c2e80-992d-11eb-8afa-09618f821796.png)
![Quảng cáo dưới sapo](https://user-images.githubusercontent.com/82023545/114131722-52ffb580-992d-11eb-9e66-4f8a733292d3.png)

**Comment by quangtruongthanh** [comment]
hi @tuansandro QC trên đầu tôi để lại rồi nhưng kích thước nó ăn theo cái site cũ, bảo bọn qc nó thay lại nhé
còn qC dưới sapo trang detail thì tôi dữ nguyên, ông xem nó là cái mã nào gửi lại tôi check xem

**Comment by tuansandro** [comment]
- Quảng cáo phía trên đó để responsive mà ông, đâu có fix kích thước, vì mobile có nhiều kích cỡ khác nhau, sao để 1 kích thước được. Nó cũng giống cái QC ở phía dưới mà ông giữ nguyên ấy. Ông xem lại xem sao vì tôi chưa thấy nó hiển thị ra quảng cáo đó nên chưa check được.

**Comment by tuansandro** [comment]
Ngoài ra kích thước mới như ông nói là bao nhiêu, để nếu trường hợp ko phải responsive thì để tôi nói bên QC lấy mã code QC mới ứng với kích thước đó xem sao

**Comment by quangtruongthanh** [comment]
cái qc trên đầu là kích thước full màn hình.
