### ISSUE TITLE
30. Tạm bỏ 2 quảng cáo để đỡ bị trắng trang

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#28]
- Trước khi anh Long chỉnh được ảnh quảng cáo cho phù hợp kích thước, Quang tạm bỏ 2 quảng cáo Tiến nông và Minh Long (như ảnh đính kèm) để tránh bị lỗi trắng trang nhé
![QC làm trắng trang](https://user-images.githubusercontent.com/82023545/114133007-8a6f6180-992f-11eb-818c-4d5993dd37bd.jpg)

**Comment by quangtruongthanh** [comment]
done
