### ISSUE TITLE
31. Click vào nhiều link trên trang chủ và ở một số trang chuyên mục thì nhảy ra giao diện trang chi tiết của DNVN hiện tại thay vì giao diện mới

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#29]
- Một số link bị lỗi dạng đó gồm:
+ Linh ở phần Nổi bật
+ Link ở phần các tin chuyên mục (giao diện home)
+ LInk ở phần quảng cáo dẫn link báo (màu vàng) ở ảnh đính kèm
![Link nhảy sang giao diện DNVN cũ](https://user-images.githubusercontent.com/82023545/114133429-43ce3700-9930-11eb-8e59-279ac10a50b2.jpg)

**Comment by quangtruongthanh** [comment]
@tuansandro ông clear cache data trình duyệt đi là được nhé
