### ISSUE TITLE
32. Tin hot nhảy làm xô lệch phần dưới ở bản Mobile

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#30]
- Hiện nhiều tin hot dài, tầm 3,4 dòng sẽ khiến cho khi chuyển từ 1 tin hot ngắn sang tin hot dài xô lệch phần dưới. Điều này khiến độc giả đang lướt đọc ở phần dưới sẽ bị khó chịu
- Giải pháp: Ở bản mobile có thể fix cứng số lượng dòng chỗ tin hot là 2 dòng, quá 2 dòng thì để dấu ba chấm (kể cả tin ngắn 1 dòng thì vẫn để thành 2 dòng để cố định lại, để khi chuyển tin khác không bị xô lệch).
- Ngoài ra hiện ở bản Android vẫn bị chữ quá to như đã báo trước đây

**Comment by quangtruongthanh** [comment]
done
