### ISSUE TITLE
33. Phần ngoại tệ ở phía trên header hiện tại đang hiển thị là GBP

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#31]
- Đổi lại thành USD
- Ngoài ra nhiều khi vàng lại nhảy sang bên Ngoại tệ
![Giá vàng, ngoại tệ chưa chuẩn](https://user-images.githubusercontent.com/82023545/114191096-3e93db00-9976-11eb-9618-4f0654794321.jpg)

**Comment by quangtruongthanh** [comment]
đây là dữ liệu sample. chưa có dữ liệu thật nên nó thế
