### ISSUE TITLE
33. Chèn link vào ảnh avatar

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#32]
- Hiện click vào ảnh bài chính chuyên mục không vào được bài, chèn thêm link bài vào ảnh đại diện
- Tương tự, các ảnh nhỏ bên cạnh cũng không có link
- Ảnh ở phần cover cũng tương tự, không có link
![Chèn link vào ảnh2](https://user-images.githubusercontent.com/82023545/114330812-bc213c00-9b6c-11eb-8b2f-18102a6aae25.jpg)
![Chèn link vào ảnh](https://user-images.githubusercontent.com/82023545/114330821-c2171d00-9b6c-11eb-9977-e0c007a5fac0.jpg)

**Comment by quangtruongthanh** [comment]
done
