### ISSUE TITLE
34. Ở sapo của các tin hiện bị tình trạng khoảng cách chữ quá rộng

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#34]
- Bỏ justify, chuyển thành căn trái
![169944686_491551248777737_6084949493522294689_n](https://user-images.githubusercontent.com/82023545/114332200-f04a2c00-9b6f-11eb-98e6-345a879285f3.png)

**Comment by longtv123456** [comment]
Quang bỏ giúp anh các class text-justify đi nhé

**Comment by quangtruongthanh** [comment]
done
