### ISSUE TITLE
36. Phần quảng cáo anh em bổ sung giúp cái chặn dưới để không bị trôi xuống đè lên phần dưới của bài

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#36]
- Tương tự như hiện tại đang hiển thị ở trang DNVN
![QC1](https://user-images.githubusercontent.com/82023545/114557094-86c33e00-9c93-11eb-9840-c6a7f1d897b9.jpg)

**Comment by quangtruongthanh** [comment]
done
