### ISSUE TITLE
37. Check lỗi Google báo khi đo tốc độ web

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#37]
- Tốc độ bản test chậm hơn so với bản hiện tại, Google cảnh báo 1 số lỗi, đặc biệt là lỗi ảnh. Tốc độ liên quan trực tiếp đến thứ hạng SEO nên nhờ anh em check hộ. Tks!

https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Ftest.doanhnghiepvn.vn%2F&tab=desktop
![222](https://user-images.githubusercontent.com/82023545/114571180-aa40b580-9ca0-11eb-8d46-877a16234e36.jpg)

**Comment by quangtruongthanh** [comment]
done
