### ISSUE TITLE
38. Chèn lại code quảng cáo ở bản Mobile test

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#38]
- Nhờ Quang trên bản Mobile bỏ cái quảng cáo hiện tại đang để ở phía trên Menu (chính cả QC top banner của bản PC responsive sang)
- Sau đó nhờ Quang chèn hộ 2 code QC này lên bản test hộ xem có ok không với nhé. **Cái MB3 ở phía trên menu, còn cái MB 1 ở dưới dưới sapo.**
[MB-3-300x600.txt](https://github.com/tuansandro/dnvn/files/6317916/MB-3-300x600.txt)
[MB-1-336x280.txt](https://github.com/tuansandro/dnvn/files/6317917/MB-1-336x280.txt)

**Comment by quangtruongthanh** [comment]
done
