### ISSUE TITLE
39. Bỏ quảng cáo này trên trang PC và cả Mobile

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#39]
- Quang bỏ giúp cái QC nào trên PC và cả mobile cái nhé (cái mobile thì thay bằng 2 cái code tôi gửi ở issue trước
![Bỏ quảng cáo](https://user-images.githubusercontent.com/82023545/114993047-99bd5480-9ec5-11eb-84b8-a8f3948e6bdf.jpg)
)

**Comment by quangtruongthanh** [comment]
done
