### ISSUE TITLE
4. Bỏ sapo ở phần các mục có cách sắp xếp song song nhau

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#4]
Bao gồm các cụm sau:
1. Chuyển đổi số, thị trường, hiệp định CPTPP, 2. Văn hóa, Khám phá, 3. Đời sống, Quốc tế, 4. English, Made in VN, 5. Pháp luật, Thể thao, 6. Tư vấn pháp luật, marcom, nhịp cầu nhân ái) 

![Bỏ sapo](https://user-images.githubusercontent.com/82023545/113685332-55290080-96f0-11eb-9bcf-32f8fdf450a6.jpg)

**Comment by quangtruongthanh** [comment]
done
