### ISSUE TITLE
44. Quang set giúp mục Multimedia về dạng mục thường giống các mục khác nhé

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#44]
- Hiện tại mục Multimedia là một mục hiển thị riêng, nhưng bởi cách hiển thị này nên các nguồn quét như Báo mới hay Cốc cốc không nhận được ảnh avatar
- Tạm thời chưa fix được thì nhờ Quang cho hiển thị như các mục khác như Thể thao, văn hóa cả giao diện chuyên mục lẫn trang đọc bài chi tiết nhé. Tks!

**Comment by quangtruongthanh** [comment]
done
