### ISSUE TITLE
5. Bỏ 1 tin ở các mục có cách hiển thị 1 tin to và 5 tin đơn hiện tại (chỉ còn 4 tin bên cạn tin chính) 

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#5]
Bao gồm các mục: Tin tức sự kiện; Hỗ trợ doanh nghiệp, Khoa học - Công nghệ; Kinh doanh và tiêu dùng

![Bỏ tin này](https://user-images.githubusercontent.com/82023545/113685650-ad600280-96f0-11eb-99a6-d81579ffb019.jpg)

**Comment by quangtruongthanh** [comment]
done
