### ISSUE TITLE
Phần nổi bật  cũng như Sapo các mục cũng bị lỗi để căn chữ nên có nhiều khoảng cách giữa các chữ

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#6]
- Nên để căn trái thì sẽ đẹp hơn
![Chữ khoảng cách nhiều, tốn diện tích](https://user-images.githubusercontent.com/82023545/113686052-10519980-96f1-11eb-92d7-d6a542d2998e.jpg)

**Comment by quangtruongthanh** [comment]
anh @longtv123456 xử lý em vụ khoảng cách chữ với
Còn vụ nó bị sát mép bên phải là do số lượng tin mà nhỏ hơn 8 là nó bị thế em đã tăng số tin lên thì hết rồi

**Comment by quangtruongthanh** [comment]
done, css mới đã fix
