### ISSUE TITLE
Không căn trái chỗ thanh menu ngang, thành ra cái biểu tượng Home bị thụt so với cái Tin hot ở dưới

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#7]
![thanh Menu bị thụt vào](https://user-images.githubusercontent.com/82023545/113686236-40993800-96f1-11eb-9ce9-9f7dd708f7fa.jpg)

**Comment by longtv123456** [comment]
Cái này là menu căn giữa nên có thể thụt hoặc thò so với dòng Tin hot
