### ISSUE TITLE
10. Menu khi click xổ ra

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#8]
Nhờ anh Long làm hộ cái chỗ xổ menu ra khi khi click vào vị trí khác ngoài menu sẽ tắt hiển thị (hiện tại phải ấn vào biểu tượng Menu 1 lần nữa mới undo được nên khá bất tiện)

**Comment by longtv123456** [comment]
Cái này khoai @quangtruongthanh viết thêm cho anh đc không

**Comment by quangtruongthanh** [comment]
em cũng ko biết :) em tưởng css có cách nào nó thu lại

**Comment by longtv123456** [comment]
thay thế đoạn này
<script type="text/javascript">
	$( document ).ready(function() {
     $('.leftmenutrigger').on('click', function(e) {
     $('.side-nav').toggleClass("open");
     e.preventDefault();
    });
});	</script>


Bằng

<script type="text/javascript">
	$(document).ready(function() {
	// jQuery code

	  $(".leftmenutrigger").on("click", function(e){
        e.preventDefault();
        e.stopPropagation();
        var offcanvas_id =  $(this).attr('data-trigger');
        $(offcanvas_id).toggleClass("show");
        $('body').toggleClass("offcanvas-active");
        $(".screen-overlay1").toggleClass("show");
		  $(".side-nav1").toggleClass("open");
    }); 


   	// Close menu when pressing ESC
    $(document).on('keydown', function(event) {
        if(event.keyCode === 27) {
           $(".offcanvas").removeClass("show");
           $("body").removeClass("overlay-active");
        }
    });

    $(".btn-close, .screen-overlay1").click(function(e){
    	$(".screen-overlay1").removeClass("show");
        $(".offcanvas").removeClass("show");
		$(".side-nav1").removeClass("open");
        $("body").removeClass("offcanvas-active");
    }); 
	
});	</script>

css anh gửi sky nhé

**Comment by quangtruongthanh** [comment]
done
