### ISSUE TITLE
11. Lỗi dọc quảng cáo

### ISSUE THREAD

**Issue by tuansandro** [tuansandro/dnvn#9]
Lỗi 2 dọc quảng cáo ở trang chi tiết, trang Chuyên mục ăn vào menu ngang, che mất biểu tượng Home, tên chuyên mục trên thành menu ngang. Ngoài ra 2 dọc quảng cáo đó ko đè lên Footer ở phần chân trang chủ 

![QC ăn vào ở trang chi tiết](https://user-images.githubusercontent.com/82023545/113686765-d339d700-96f1-11eb-9653-d29cb551e1cf.jpg)
![QC ăn vào trang chuyên mục](https://user-images.githubusercontent.com/82023545/113686768-d5039a80-96f1-11eb-9dd0-48fe63ff6238.jpg)
![QC ăn vào chân trang](https://user-images.githubusercontent.com/82023545/113686770-d59c3100-96f1-11eb-9df2-88d0457052ca.jpg)

**Comment by quangtruongthanh** [comment]
anh @longtv123456 xử hộ em câu này của tuấn "Ngoài ra 2 dọc quảng cáo đó ko đè lên Footer ở phần chân trang chủ"
